name: RV Noobz
favicon: null
layout_spectrum: 0.2059250664897263
typography_spectrum: 0.37508
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.5815158446785063
  lightness: 0.8884893388021737
  saturation: 0.6124932139646262
  rhythmicContrast: 0.39933795062825084
purpose: []
