name: RV Noobz
favicon: null
layout_spectrum: 0.2059250664897263
typography_spectrum: 0.37508
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#cc9339'
    - '#2a0d00'
    - '#a44600'
    - '#a2661e'
    - '#f4c165'
  brandStrength: 0.1875
  lightness: 0.8884893388021737
  saturation: 0.1875
  rhythmicContrast: 0.39933795062825084
purpose: []
